export const VOICE_TRAINING_EXAMPLES = [
  { input: "Juega 100 al 23 en Nacional", intent: "CREATE_PLAY" },
  { input: "Ponme 50 al 45 en La Primera", intent: "CREATE_PLAY" },
  { input: "Palé 12 con 45 por 20 en Loteka", intent: "CREATE_PLAY" },
  { input: "Tripleta 12 45 80 por 10 en Nacional", intent: "CREATE_PLAY" },
  { input: "Confirma", intent: "CONFIRM_PLAY" },
  { input: "Cancela", intent: "CANCEL_CURRENT_DRAFT" },
  { input: "Cambia el monto a 200", intent: "MODIFY_DRAFT_PLAY" },
  { input: "Repite la última jugada", intent: "REPEAT_LAST_PLAY" },
  { input: "Cuánto balance tengo", intent: "GET_BALANCE" },
  { input: "Muéstrame mis tickets", intent: "LIST_TICKETS" },
  { input: "Qué salió en Nacional", intent: "GET_LOTTERY_RESULT" },
  { input: "Muestra mi QR", intent: "SHOW_PLAYER_QR" },
  { input: "Quiero recargar", intent: "OPEN_RECHARGE" },
  { input: "Juega al 23 en Nacional", intent: "CREATE_PLAY", missing: ["amount"] },
  { input: "Juega 100 en Nacional", intent: "CREATE_PLAY", missing: ["numbers"] },
  { input: "Juega 100 al 23", intent: "CREATE_PLAY", missing: ["lotteries"] },
  { input: "asdfgh qwerty", intent: "UNKNOWN" },
] as const;
